# Generated by Django 3.2.9 on 2021-12-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='folio',
            field=models.CharField(default='prueba1', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bodyattribute',
            name='folio',
            field=models.CharField(default='prueba1', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bodyattribute_historyclinic',
            name='folio',
            field=models.CharField(default='prueba1', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='folio',
            field=models.CharField(default='prueba1', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_membership',
            name='folio',
            field=models.CharField(default='fs432', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyclinic',
            name='folio',
            field=models.CharField(default='fsf43', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionalsituation',
            name='folio',
            field=models.CharField(default='csd3', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeextrainformation',
            name='folio',
            field=models.CharField(default='fsd4', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeextrainformation_historyclinic',
            name='folio',
            field=models.CharField(default='dssfs4', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
