# Generated by Django 3.2.3 on 2022-01-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='folio',
            field=models.CharField(default='dsadsa3', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_details_product',
            name='folio',
            field=models.CharField(default='dsdas', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
