# Generated by Django 3.2.3 on 2022-01-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20220104_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='folio',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
