# Generated by Django 3.2.3 on 2022-01-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='folio',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
