# Generated by Django 3.2.3 on 2022-01-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='folio',
            field=models.CharField(default='fdadss', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyinventory',
            name='folio',
            field=models.CharField(default='sdfsdfsd', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='folio',
            field=models.CharField(default='fdas', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationtype',
            name='folio',
            field=models.CharField(default='asdsadasas', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='folio',
            field=models.CharField(default='free4', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='folio',
            field=models.CharField(default='sad43', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='folio',
            field=models.CharField(default='asdas454', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
