# Generated by Django 3.2.9 on 2021-12-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='folio',
            field=models.CharField(default='dfsd', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyinventory',
            name='folio',
            field=models.CharField(default='dfsd', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='folio',
            field=models.CharField(default='dfsd4', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationtype',
            name='folio',
            field=models.CharField(default='sdfs3', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='folio',
            field=models.CharField(default='dfsd4', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='folio',
            field=models.CharField(default='dfsdfsd4', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='folio',
            field=models.CharField(default='sdasd4353', max_length=10),
            preserve_default=False,
        ),
    ]
